### ISSUE TITLE
Mono repo migration: checklist (issue/PR migration)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5252]
Final list of items to do after migrating to mono repo.

* [ ] Migrate issues
    * [ ] ND4J
    * [x] ND4S
    * [ ] Libnd4j
    * [x] DataVec
    * [x] Arbiter
    * [x] RL4J
    * [x] gym-java-client
    * [x] ScalNet
    * [x] Jumpy
* [ ] Close existing PRs (if any) and provide migration advice
    * [ ] ND4J
    * [x] ND4S
    * [ ] Libnd4j
    * [x] DataVec
    * [x] Arbiter
    * [x] RL4J
    * [x] gym-java-client
    * [x] ScalNet
    * [x] Jumpy
* [ ] Update readmes and archive old repositories
    * [ ] ND4J
    * [x] ND4S
    * [ ] Libnd4j
    * [x] DataVec
    * [x] Arbiter
    * [x] RL4J
    * [x] gym-java-client
    * [x] ScalNet
    * [x] Jumpy

**Comment by AlexDBlack** [comment]
@crockpotveggies What are you using for github issue migration for the docs repo?
It's some sort of github plugin or something, right?
(Just looking at it for ND4J - the remaining repos are probably small enough to migrate manually)
